name: Build and Run Weather Desktop Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Name: Weather_Desktop_Application.sln
      Wap_Project_Directory: Weather_Desktop_Application

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore NuGet packages
        run: dotnet restore $env:Solution_Name

      - name: Build the application
        run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

      - name: Run the application
        run: |
          cd $env:Wap_Project_Directory/bin/${{ matrix.configuration }}/net6.0-windows10.0.19041.0/AppPackages
          .\Weather_Desktop_Application.exe

